### Application
scout.application.name=Gourmetgate
scout.application.version=0.0.1

### UI
scout.ui.locales=en

### Storage location for FileSystemUserPreferencesStorageService
scout.client.userArea=${user.home}/gourmetgate-dev

### Environment
scout.devMode=true

import=classpath:dev.db.config.properties
