### persistence
persistence.sql.jdbc.mapping.name=${DATABASE_URL}
persistence.sql.password=${POSTGRES_PASSWORD}
persistence.sql.username=${POSTGRES_USER}
persistence.sql.driver=org.postgresql.Driver
persistence.sql.dialect=POSTGRES
persistence.sql.schema=${DATABASE_SCHEMA}
