### Application
scout.application.name=Gourmetgate
scout.application.version=${gourmetgate.version}

### UI
scout.ui.locales=en

### Storage location for FileSystemUserPreferencesStorageService
scout.client.userArea=/tmp/gourmetgate

### persistence
persistence.sql.jdbc.mapping.name=${DATABASE_URL}
persistence.sql.password=${POSTGRES_PASSWORD}
persistence.sql.username=${POSTGRES_USER}
persistence.sql.driver=org.postgresql.Driver
persistence.sql.dialect=POSTGRES
persistence.sql.schema=${DATABASE_SHEMA}
### Auth
auth.privateKey=${PRIVATE_KEY}
auth.publicKey=${PUBLIC_KEY}
auth.accessTokenExpiration=900
auth.refreshTokenExpiration=604800
