name: Jasmine Tests

on:
  pull_request:
    branches:
      - develop

jobs:
  jasmin-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: ./.github/actions/setup
      - name: Install dependencies
        run: pnpm install
      - name: Run Jasmine tests
        working-directory: ./gourmetgate.ui
        run: pnpm run test:ci
